#!/bin/bash

## got tired of writing make clean and make so many times
clear
make clean
make
echo 			## makes a new line
./scheduler $1 	## $1 is the args -- for the number of threads you want

echo -e '\n\ncleaning the project after use\n\n'
make clean

